export const CHARACTER_MAP: Record<string, { name: string; theater: string }> = {
    "101": { name: "Otori Kokona", theater: "Sirius" },
    "102": { name: "Shizuka", theater: "Sirius" },
    "103": { name: "Kathrina Griebel", theater: "Sirius" },
    "104": { name: "Niizuma Yae", theater: "Sirius" },
    "105": { name: "Yanagiba Panda", theater: "Sirius" },
    "106": { name: "Sasuga Chisa", theater: "Sirius" },
    "107": { name: "Hiiragi Noa", theater: "Sirius" },
    "110": { name: "Kudou Hana", theater: "Sirius" },
    "111": { name: "Yamabuki Shamo", theater: "Sirius" },
    "201": { name: "Renjakuno Hatsumi", theater: "Eden" },
    "202": { name: "Karasumori Daikoku", theater: "Eden" },
    "203": { name: "Toneri Nikako", theater: "Eden" },
    "204": { name: "Yorozu Iruru", theater: "Eden" },
    "205": { name: "Fudeshima Shigure", theater: "Eden" },
    "206": { name: "Tetra", theater: "Eden" },
    "301": { name: "Senju Koyomi", theater: "Gingaza" },
    "306": { name: "Senju Koyomi", theater: "Gingaza" },
    "302": { name: "Ramona Wolf", theater: "Gingaza" },
    "303": { name: "Wang Xue", theater: "Gingaza" },
    "304": { name: "Lilja Kurtbay", theater: "Gingaza" },
    "305": { name: "Yonaguni Hikari", theater: "Gingaza" },
    "401": { name: "Senju Iroha", theater: "Gekidan Denki" },
    "408": { name: "Senju Iroha", theater: "Gekidan Denki" },
    "409": { name: "Senju Iroha", theater: "Gekidan Denki" },
    "402": { name: "Shiromaru Mito", theater: "Gekidan Denki" },
    "403": { name: "Akiru Kamira", theater: "Gekidan Denki" },
    "404": { name: "Nekoashi Tsubomi", theater: "Gekidan Denki" },
    "405": { name: "Motosu Towa", theater: "Gekidan Denki" },
    "406": { name: "Kaname", theater: "Gekidan Denki" },
    "407": { name: "Machiko", theater: "Gekidan Denki" },
    "501": { name: "Therese Griebel", theater: "Others" },
    "502": { name: "Nanase Chikage", theater: "Others" },
    "503": { name: "Fukushi Rinko", theater: "Others" },
    "504": { name: "Hikawa", theater: "Others" },
    "505": { name: "Yushima", theater: "Others" },
    "506": { name: "Riko", theater: "Others" },
    "507": { name: "Anzu", theater: "Others" },
    "508": { name: "Koharu", theater: "Others" },
    "509": { name: "Konno Shiori", theater: "Others" },
    "511": { name: "Komae Chiho", theater: "Others" },
    // "512": { name: "", theater: "Others" },
    "513": { name: "Christina", theater: "Others" },
    "514": { name: "Kagamihara Nadeshiko", theater: "Yuru Camp" },
    "515": { name: "Shima Rin", theater: "Yuru Camp" },
    "516": { name: "Nishizumi Miho", theater: "Girls und Panzer" },
    "517": { name: "Takabe Saori", theater: "Girls und Panzer" },
    "518": { name: "Isuzu Hana", theater: "Girls und Panzer" },
    "519": { name: "Akiyama Yukari", theater: "Girls und Panzer" },
    "520": { name: "Reizei Mako", theater: "Girls und Panzer" },
    "521": { name: "Renjakuno Futaba", theater: "Others" },
    "522": { name: "Hibari", theater: "Others" },
    "601": { name: "Komae Chiho", theater: "Others" },
    "901": { name: "Takami Chika", theater: "Love Live! Sunshine!!" },
    "902": { name: "Sakurauchi Riko", theater: "Love Live! Sunshine!!" },
    "904": { name: "Kurosawa Dia", theater: "Love Live! Sunshine!!" },
    "906": { name: "Tsushima Yoshiko", theater: "Love Live! Sunshine!!" },
    "909": { name: "Kurosawa Ruby", theater: "Love Live! Sunshine!!" },
};

export const THEATER_ORDER = ["Sirius", "Eden", "Gingaza", "Gekidan Denki", "Others", "Yuru Camp", "Girls und Panzer", "Love Live! Sunshine!!"];
