export const CHARACTER_MAP: Record<string, { name: string; theater: string }> = {
    "101": { name: "Otori Kokona", theater: "Sirius" },
    "102": { name: "Shizuka", theater: "Sirius" },
    "103": { name: "Kathrina Griebel", theater: "Sirius" },
    "104": { name: "Niizuma Yae", theater: "Sirius" },
    "105": { name: "Yanagiba Panda", theater: "Sirius" },
    "106": { name: "Sasuga Chisa", theater: "Sirius" },
    "107": { name: "Hiiragi Noa", theater: "Sirius" },
    "110": { name: "Kudou Hana", theater: "Sirius" },
    "201": { name: "Renjakuno Hatsumi", theater: "Eden" },
    "202": { name: "Karasumori Daikoku", theater: "Eden" },
    "203": { name: "Toneri Nikako", theater: "Eden" },
    "204": { name: "Yorozu Iruru", theater: "Eden" },
    "205": { name: "Fudeshima Shigure", theater: "Eden" },
    "206": { name: "Tetra", theater: "Eden" },
    "301": { name: "Senju Koyomi", theater: "Gingaza" },
    "306": { name: "Senju Koyomi", theater: "Gingaza" },
    "302": { name: "Ramona Wolf", theater: "Gingaza" },
    "303": { name: "Wang Xue", theater: "Gingaza" },
    "304": { name: "Lilja Kurtbay", theater: "Gingaza" },
    "305": { name: "Yonaguni Hikari", theater: "Gingaza" },
    "401": { name: "Senju Iroha", theater: "Gekidan Denki" },
    "408": { name: "Senju Iroha", theater: "Gekidan Denki" },
    "409": { name: "Senju Iroha", theater: "Gekidan Denki" },
    "402": { name: "Shiromaru Mito", theater: "Gekidan Denki" },
    "403": { name: "Akiru Kamira", theater: "Gekidan Denki" },
    "404": { name: "Nekoashi Tsubomi", theater: "Gekidan Denki" },
    "405": { name: "Motosu Towa", theater: "Gekidan Denki" },
    "406": { name: "Kaname", theater: "Gekidan Denki" },
    "407": { name: "Machiko", theater: "Gekidan Denki" },
};

export const THEATER_ORDER = ["Sirius", "Eden", "Gingaza", "Gekidan Denki"];
